Models/ErrorViewModel.cs
namespace EfDotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CategoryController.cs
using System;
using EfDotnet.DataContext;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EfDotnet.Controllers;

// [Route("[controller]")]
public class CategoryController : Controller
{
    private readonly ApplicationDbContext _context;
    public CategoryController(ApplicationDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult Index()
    {
        IEnumerable<CategoryEntity> categories = _context.CategoryEntities.ToList();
        return View(categories);
    }

    [HttpGet("[action]")]
    public IActionResult Details(int? id)
    {
        CategoryEntity category = _context.CategoryEntities.Find(id);
        return View(category);
    }

    [HttpGet("[action]")]
    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Save([Bind("CategoryCode, CategoryName, Description")] CategoryEntity request)
    {
        // add ke entity
        _context.CategoryEntities.Add(request);
        // commit to database
        _context.SaveChanges();

        return Redirect("Index");
    }

    [HttpGet("[action]")]
    public IActionResult Edit(int? id)
    {
        var entity = _context.CategoryEntities.Find(id);
        return View(entity);
    }

    [HttpGet("[action]")]
    public IActionResult Delete(int? id)
    {
        var entity = _context.CategoryEntities.Find(id);
        if (entity == null)
        {
            return Redirect("Index");
        }
        // remove from entity
        _context.CategoryEntities.Remove(entity);
        // commit to database
        _context.SaveChanges();
        return Redirect("Index");
    }

    [HttpPost]
    public IActionResult Update([Bind("Id,CategoryCode, CategoryName, Description")] CategoryEntity request)
    {
        // update entity
        _context.CategoryEntities.Update(request);
        // commit to database
        _context.SaveChanges();
        return Redirect("Index");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EfDotnet.Models;

namespace EfDotnet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Category/Add.cshtml
@model EfDotnet.DataContext.CategoryEntity
@{
    ViewData["Title"] = "Category View Data";
}

<h2>Form Add Category</h2>

<form asp-controller="Category" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CategoryCode"></label>
        <input asp-for="CategoryCode" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="CategoryName"></label>
        <input asp-for="CategoryName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<a asp-action="GetAll" class="btn btn-sm btn-danger">Back</a>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Category/Details.cshtml
@model EfDotnet.DataContext.CategoryEntity
@{
    ViewData["Title"] = "Detail Category";
}

<h2>Detail Category</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Code</th>
        <td>@Model.CategoryCode</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>@Model.CategoryName</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
</table>
<a asp-action="GetAll" class="btn btn-sm btn-danger">Back</a>

Views/Category/Edit.cshtml
@model EfDotnet.DataContext.CategoryEntity
@{
    ViewData["Title"] = "Category Edit Data";
}

<h2>Form Edit Category</h2>

<form asp-controller="Category" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="CategoryCode"></label>
        <input asp-for="CategoryCode" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="CategoryName"></label>
        <input asp-for="CategoryName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>
<a asp-action="GetAll" class="btn btn-sm btn-danger">Back</a>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Category/Index.cshtml
@model IEnumerable<EfDotnet.DataContext.CategoryEntity>

@{
    ViewData["Title"] = "Category View GetAll";
}

<h2>Category Get All</h2>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Code</th>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.CategoryCode</td>
                <td>@item.CategoryName</td>
                <td>@item.Description</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Add" class="btn btn-sm btn-primary">Add</a>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfDotnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EfDotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EfDotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EfDotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>